### ISSUE TITLE
Unescaped quotes in package.json

### ISSUE THREAD

**Issue by irontitan76** [yogaboll/react-npm-component-starter#3]
For those Windows users, the `"npm run dev"` script should be `"dev": "concurrently \"npm run lib:watch\" \"npm run docs\""`. I believe this'll also work on Unix-based machines.

**Comment by markusenglund** [comment]
Oh, that's my bad. I'll boot up Windows and take a look at it.

**Comment by markusenglund** [comment]
I fixed it with your suggested script which seems to work everywhere. Thanks!
