### ISSUE TITLE
How to import and use the npm component in another project?

### ISSUE THREAD

**Issue by Fensterbank** [yogaboll/react-npm-component-starter#7]
Thank you very much for your boilerplate and explanations.
I work a lot with react, but did not yet created a reusable component as an npm packge.

I followed your instructions and wanted to test the created package in a react app built with `create-react-app`.
In this example I installed the package `connect-widgets` (which is my npm package with components) directly from github.
![grafik](https://user-images.githubusercontent.com/1684826/41051812-688235b6-69b7-11e8-8fef-90ae7db29f80.png)

Unfortunateley I have no clue how I can actually use the component now.
Isn't there a `index.js` missing in the boilerplate, which actually exports the things to the projects importing this package?

`import MySuperCoolComponent from 'connect-widgets';`
results in
![grafik](https://user-images.githubusercontent.com/1684826/41051919-c34045d8-69b7-11e8-960c-19bc22cea8ab.png)

`import MySuperCoolComponent from 'connect-widgets/src/lib';`
results in
![grafik](https://user-images.githubusercontent.com/1684826/41051874-9e54598a-69b7-11e8-9eb5-415c5b7c8524.png)

Did I forgot a important step here?
When I take a look to the folder `node_modules/connect-widgets` I don't find a transpiled `lib` folder, only the untranspiled `src`.
Since `/lib` is part of your `.gitignore` I think it works as expected, but then there is something missing...
![grafik](https://user-images.githubusercontent.com/1684826/41052323-be4c4f3a-69b8-11e8-8e5a-4276e93a9de1.png)

The goal would be to have imports like
`import { SuperComponent, FancyComponent, UglyComponent } from "connect-widgets"`
but I could not figure it out yet.

Thanks for help.

**Comment by markusenglund** [comment]
As you pointed out, the /lib folder is listed in .gitignore and therefore not uploaded to Github. If you remove it from .gitignore and commit the lib folder and push to your repo, you should be able to install your component directly from GitHub.

The reason why I still chose to put the lib-folder inside gitignore is because the typical use case is to publish to npm. Npm looks at the .npmignore file instead of .gitignore so the lib folder will be included in the npm repo by default.

Hope that helps!

**Comment by Fensterbank** [comment]
Thank you for clarification. This makes sense.
While I used Github to just test my "private npm package" I provoked a problem people normally don't have.
With a real npm repository and npm publish it works as expected!
